spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false #aviso de seguridad SSL desactivado, para evitar logs
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #Al arrancar el Server, comprobara que las Entity correspondan con las TBL
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false #No admita cache, para buen funcionamiento con spring loaded, ver en caliente los cambios.